spring:
  profiles:
    active: master
  application:
    name: challenge-app-backend
  devtools:
    restart:
      enabled: true
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: khb0915
jwt:
  accessTokenValidity: 3d
  refreshTokenValidity: 5d
  secret: YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=
springdoc:
  model-and-view-allowed: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: rest-api-doc.html
    default-models-expand-depth: -1

logging:
  config: classpath:logback-spring.xml
  charset:
    console: UTF-8
    file: UTF-8
custom:
  path:
    upload-images: ''

---

spring:
  profiles:
    active: develop
  application:
    name: challenge-app-backend
  devtools:
    restart:
      enabled: true
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: khb0915
jwt:
  accessTokenValidity: 3d
  refreshTokenValidity: 5d
  secret: YnBucy1oZXBjLWJhY2tlbmQtanNvbndlYnRva2VuLXNlY3JldEtleQo=
springdoc:
  model-and-view-allowed: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: rest-api-doc.html
    default-models-expand-depth: -1

logging:
  config: classpath:logback-spring.xml
  charset:
    console: UTF-8
    file: UTF-8
custom:
  path:
    upload-images: ''